### ISSUE TITLE
프로젝트 윤곽잡기

### ISSUE THREAD

**Issue by xgate** [sultudy/waterfall#1]
simple한 stream server <-> client 만들기

**Comment by xgate** [comment]
@djkim005 전에 보여주신거 쌩 http로 하셨었던가요? asStream 이런 메소드를 못찾겠어서요 ㅋㅋ (twitter4j에서 내부적으로 만들어놓은건 있어요)

chunked response로 해봤습니다.

@rfchief

**Comment by djkim005** [comment]
@xgate 
클라이언트는 twitter4j 라이브러리를 사용했었고, asSream은 twitter4j.internal.http.HttpResponse 의 메써드~

@rfchief

**Comment by djkim005** [comment]
[INFO]
com.sun.net.httpserver.HttpServer 얘가 원래 그런건지, 설정을 해야하는건지는 모르겠으나,
테스트를 해보니, 현재 동시접속을 제대로 처리하지 못하고 있음.
하나의 요청이 끝나야 다음 요청을 처리함.

**Comment by xgate** [comment]
@djkim005 그렇군요 -_-;; 혹시 동시접속 처리가 안되나..;; 알아봐야겠네요 ㅋ
