### ISSUE TITLE
서블릿 엔진(라이브러리)를 사용하지 않는 simple stream server 구현

### ISSUE THREAD

**Issue by djkim005** [sultudy/waterfall#2]
- 전통적인 io 방식과 nio 방식으로 구현해 보고 비교해보기
  - 전통적인 socket thread 모델로 구현
  - nio asynch 모델로 구현
  - nio non-blocking 모델로 구현
- 모델 방식 이해를 위한 코드로 구조나 테스트 코드 등은 신경쓰지 않겠음~^^;

**Comment by xgate** [comment]
:+1:

**Comment by xgate** [comment]
:100:
